### ISSUE TITLE
Enable strict mode

### ISSUE THREAD

**Issue by abataille** [maxcanna/node-lightify-rest#4]
Seems that you forgot 'use strict'; in the lib/request.js.

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)

[Click here](https://app.gitmagic.io/maxcanna/node-lightify-rest/4/61e9d5b1-d2a5-4ba2-8141-1aaa504947be/85b73d70-69c3-42ae-aff1-29767a449b71) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by maxcanna** [comment]
Hi, thank you for noticing that. You're absolutely right. 
Feel free to open a PR to fix it. 

Take a moment to fix this issue too. 

Thanks again

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:

**Comment by maxcanna** [comment]
Fixed in #5, closing.
